const json = (schema: Record<string, unknown>) => ({ 'application/json': { schema } });

const errorResponses = {
  '400': { description: 'Solicitud inválida', content: json({ $ref: '#/components/schemas/Error' }) },
  '401': { description: 'Clave API ausente o inválida', content: json({ $ref: '#/components/schemas/Error' }) },
  '403': { description: 'Permiso insuficiente', content: json({ $ref: '#/components/schemas/Error' }) },
  '429': { description: 'Límite de frecuencia excedido', content: json({ $ref: '#/components/schemas/Error' }) },
};

const integrationHeader = { name: 'X-Zinto-Integration-Id', in: 'header', required: true, schema: { type: 'string', format: 'uuid' }, description: 'Identificador público aleatorio de la integración CRM creada en Zinto.' };
const idempotencyHeader = { name: 'Idempotency-Key', in: 'header', required: true, schema: { type: 'string', minLength: 8, maxLength: 128 }, description: 'Clave única para reintentos seguros durante 24 horas.' };

export function getApiV2OpenApiDocument() {
  return {
    openapi: '3.1.0',
    info: {
      title: 'Zinto CRM — API bidireccional',
      version: '2.0.0',
      description: 'Contrato oficial para sincronizar contactos, conversaciones, mensajes, agenda, pipeline y campañas entre un CRM y Zinto. Antes de realizar peticiones protegidas, un administrador debe crear una integración CRM en Configuración → Acceso API → Integraciones CRM, copiar su Integration ID y asociar una API Key con los permisos mínimos necesarios.',
    },
    servers: [{ url: 'https://crm.zinto.app/api/v2', description: 'Producción' }, { url: 'https://sandbox.crm.zinto.app/api/v2', description: 'Sandbox (si está habilitado)' }],
    tags: [{ name: 'Disponibilidad' }, { name: 'Administración' }, { name: 'Contactos' }, { name: 'Mensajes' }, { name: 'Media' }, { name: 'Lectura' }, { name: 'Plantillas' }, { name: 'Campañas' }, { name: 'Agenda' }, { name: 'Pipeline' }, { name: 'Sincronización' }],
    paths: {
      '/health': { get: { tags: ['Disponibilidad'], summary: 'Comprobar disponibilidad', responses: { '200': { description: 'API disponible', content: json({ $ref: '#/components/schemas/Health' }) } } } },
      '/openapi.json': { get: { tags: ['Disponibilidad'], summary: 'Descargar contrato OpenAPI', responses: { '200': { description: 'Documento OpenAPI JSON' } } } },
      '/postman.json': { get: { tags: ['Disponibilidad'], summary: 'Descargar colección Postman', responses: { '200': { description: 'Colección Postman JSON' } } } },
      '/guide.md': { get: { tags: ['Disponibilidad'], summary: 'Descargar guía Markdown', responses: { '200': { description: 'Guía completa en Markdown' } } } },
      '/capabilities': { get: { tags: ['Administración'], summary: 'Consultar permisos y eventos', security: [{ bearerAuth: [] }], responses: { '200': { description: 'Capacidades de la integración' }, ...errorResponses } } },
      '/contacts/{externalId}': { put: { tags: ['Contactos'], summary: 'Crear o actualizar contacto', security: [{ bearerAuth: [] }], parameters: [{ name: 'externalId', in: 'path', required: true, schema: { type: 'string' } }, integrationHeader], requestBody: { required: true, content: json({ $ref: '#/components/schemas/ContactInput' }) }, responses: { '200': { description: 'Contacto actualizado (la respuesta puede incluir avatarUrl si Zinto tiene la foto de perfil de WhatsApp del contacto)' }, '201': { description: 'Contacto creado (la respuesta puede incluir avatarUrl si Zinto tiene la foto de perfil de WhatsApp del contacto)' }, ...errorResponses } } },
      '/messages': { post: { tags: ['Mensajes'], summary: 'Enviar mensaje (texto y/o media) desde el CRM', description: 'Requiere `messages:send`. Si se incluye `media`, además requiere `media:upload`. Debe enviarse exactamente uno de `text` (opcionalmente con `media` como caption), `media`, `template`, `reaction`, `location`, o `interactive`.', security: [{ bearerAuth: [] }], parameters: [integrationHeader, idempotencyHeader], requestBody: { required: true, content: json({ $ref: '#/components/schemas/MessageInput' }) }, responses: { '202': { description: 'Mensaje aceptado para entrega' }, ...errorResponses } } },
      '/messages/{messageId}/read': { post: { tags: ['Mensajes'], summary: 'Marcar un mensaje recibido como leído', description: 'Requiere `messages:send`. `messageId` es el `data.id` de un mensaje propio de esta empresa (recibido, no enviado) — no un identificador de WhatsApp. Solo canales WhatsApp Official.', security: [{ bearerAuth: [] }], parameters: [{ name: 'messageId', in: 'path', required: true, schema: { type: 'integer', minimum: 1 } }, integrationHeader], responses: { '200': { description: 'Mensaje marcado como leído' }, ...errorResponses } } },
      '/media/upload': { post: { tags: ['Media'], summary: 'Subir un archivo y obtener su URL', description: 'Requiere `media:upload`. multipart/form-data con el campo `file` (imagen, vídeo, audio o documento; máx. 10&nbsp;MB). Use la `url` devuelta en `POST /messages` (`media.url`) para enviarla por WhatsApp.', security: [{ bearerAuth: [] }], parameters: [integrationHeader], requestBody: { required: true, content: { 'multipart/form-data': { schema: { type: 'object', required: ['file'], properties: { file: { type: 'string', format: 'binary' } } } } } }, responses: { '201': { description: 'Archivo subido', content: json({ $ref: '#/components/schemas/MediaUploadOutput' }) }, ...errorResponses } } },
      '/media': { get: { tags: ['Media'], summary: 'Descargar un archivo multimedia recibido o una foto de perfil', description: 'Requiere `media:read`. `type` y `filename` llegan ya resueltos en `data.media.url` de `message.received` o en `avatarUrl`/`data.contact.avatar_url`; solo es accesible para la empresa dueña del mensaje o contacto.', security: [{ bearerAuth: [] }], parameters: [{ name: 'type', in: 'query', required: true, schema: { type: 'string', enum: ['image', 'video', 'audio', 'document', 'profile_pictures'] } }, { name: 'filename', in: 'query', required: true, schema: { type: 'string' } }, integrationHeader], responses: { '200': { description: 'Contenido binario del archivo' }, ...errorResponses, '404': { description: 'Archivo inexistente o de otra empresa', content: json({ $ref: '#/components/schemas/Error' }) } } } },
      '/channels': { get: { tags: ['Lectura'], summary: 'Listar canales de la empresa', description: 'Requiere `channels:read`. Es la forma de descubrir el `channelId` que se usa en `POST /messages` y en el filtro `channelId` de `GET /conversations`.', security: [{ bearerAuth: [] }], parameters: [integrationHeader], responses: { '200': { description: 'Lista de canales', content: json({ $ref: '#/components/schemas/ChannelsListOutput' }) }, ...errorResponses } } },
      '/conversations': { get: { tags: ['Lectura'], summary: 'Listar conversaciones de la empresa', description: 'Requiere `conversations:read`. Admite los filtros opcionales `channelId`, `status` e `isGroup`, y paginación `page`/`limit` (por defecto 20, máximo 100).', security: [{ bearerAuth: [] }], parameters: [integrationHeader, { name: 'channelId', in: 'query', schema: { type: 'integer', minimum: 1 }, description: 'Filtra por canal.' }, { name: 'status', in: 'query', schema: { type: 'string' }, description: 'Filtra por estado de la conversación.' }, { name: 'isGroup', in: 'query', schema: { type: 'string', enum: ['true', 'false'] }, description: 'Filtra conversaciones grupales (true) o individuales (false).' }, { name: 'page', in: 'query', schema: { type: 'integer', minimum: 1, default: 1 } }, { name: 'limit', in: 'query', schema: { type: 'integer', minimum: 1, maximum: 100, default: 20 }, description: 'Por defecto 20, máximo 100.' }], responses: { '200': { description: 'Lista paginada de conversaciones', content: json({ $ref: '#/components/schemas/ConversationsListOutput' }) }, ...errorResponses } } },
      '/messages/{messageId}/status': { get: { tags: ['Lectura'], summary: 'Consultar el estado de entrega de un mensaje', description: 'Requiere `messages:read`. `messageId` es el `data.id` devuelto por `POST /messages`.', security: [{ bearerAuth: [] }], parameters: [{ name: 'messageId', in: 'path', required: true, schema: { type: 'integer', minimum: 1 } }, integrationHeader], responses: { '200': { description: 'Estado del mensaje', content: json({ $ref: '#/components/schemas/MessageStatusOutput' }) }, ...errorResponses, '404': { description: 'Mensaje inexistente o de otra empresa (misma respuesta en ambos casos)', content: json({ $ref: '#/components/schemas/Error' }) } } } },
      '/templates': {
        get: { tags: ['Plantillas'], summary: 'Listar plantillas de WhatsApp de la empresa', description: 'Requiere `templates:read`.', security: [{ bearerAuth: [] }], parameters: [integrationHeader], responses: { '200': { description: 'Lista de plantillas', content: json({ $ref: '#/components/schemas/TemplatesListOutput' }) }, ...errorResponses } },
        post: { tags: ['Plantillas'], summary: 'Crear una plantilla y someterla a aprobación de Meta', description: 'Requiere `templates:write`. Somete la plantilla a WhatsApp; el estado inicial suele ser `pending` hasta que Meta la revisa (consulte `GET /templates/{templateId}` para el estado actualizado). Requiere `Idempotency-Key`: un reintento con la misma clave y el mismo cuerpo no vuelve a someter la plantilla a Meta.', security: [{ bearerAuth: [] }], parameters: [integrationHeader, idempotencyHeader], requestBody: { required: true, content: json({ $ref: '#/components/schemas/CreateTemplateInput' }) }, responses: { '201': { description: 'Plantilla creada y sometida a Meta', content: json({ $ref: '#/components/schemas/TemplateOutput' }) }, ...errorResponses } },
      },
      '/templates/{templateId}': {
        get: { tags: ['Plantillas'], summary: 'Consultar una plantilla', description: 'Requiere `templates:read`.', security: [{ bearerAuth: [] }], parameters: [{ name: 'templateId', in: 'path', required: true, schema: { type: 'integer', minimum: 1 } }, integrationHeader], responses: { '200': { description: 'Plantilla', content: json({ $ref: '#/components/schemas/TemplateOutput' }) }, ...errorResponses, '404': { description: 'Plantilla inexistente o de otra empresa', content: json({ $ref: '#/components/schemas/Error' }) } } },
        patch: { tags: ['Plantillas'], summary: 'Actualizar los campos editables de una plantilla', description: 'Requiere `templates:write`. Solo admite `description` e `isActive`; el contenido aprobado por Meta no se puede editar (elimine y cree una nueva plantilla).', security: [{ bearerAuth: [] }], parameters: [{ name: 'templateId', in: 'path', required: true, schema: { type: 'integer', minimum: 1 } }, integrationHeader], requestBody: { required: true, content: json({ $ref: '#/components/schemas/UpdateTemplateInput' }) }, responses: { '200': { description: 'Plantilla actualizada', content: json({ $ref: '#/components/schemas/TemplateOutput' }) }, ...errorResponses, '404': { description: 'Plantilla inexistente o de otra empresa', content: json({ $ref: '#/components/schemas/Error' }) } } },
        delete: { tags: ['Plantillas'], summary: 'Eliminar una plantilla', description: 'Requiere `templates:write`. Elimina la plantilla de Zinto; no la elimina de Meta.', security: [{ bearerAuth: [] }], parameters: [{ name: 'templateId', in: 'path', required: true, schema: { type: 'integer', minimum: 1 } }, integrationHeader], responses: { '200': { description: 'Plantilla eliminada' }, ...errorResponses, '404': { description: 'Plantilla inexistente o de otra empresa', content: json({ $ref: '#/components/schemas/Error' }) } } },
      },
      '/webhook': {
        get: { tags: ['Administración'], summary: 'Consultar la configuración del webhook de esta integración', description: 'Requiere `webhooks:manage`. Nunca devuelve el secreto — solo si hay uno configurado (`secretConfigured`).', security: [{ bearerAuth: [] }], parameters: [integrationHeader], responses: { '200': { description: 'Configuración del webhook', content: json({ $ref: '#/components/schemas/WebhookConfigOutput' }) }, ...errorResponses, '404': { description: 'Integración inexistente', content: json({ $ref: '#/components/schemas/Error' }) } } },
        patch: { tags: ['Administración'], summary: 'Actualizar la URL del webhook, o rotar su secreto', description: 'Requiere `webhooks:manage`. `url: null` elimina la URL configurada. `rotateSecret: true` genera un secreto nuevo (invalida el anterior). El secreto solo se devuelve en la respuesta cuando se genera uno nuevo en esta misma llamada (primera vez que se configura `url`, o `rotateSecret: true`) — guárdelo entonces, no se puede volver a consultar.', security: [{ bearerAuth: [] }], parameters: [integrationHeader], requestBody: { required: true, content: json({ $ref: '#/components/schemas/WebhookConfigInput' }) }, responses: { '200': { description: 'Configuración actualizada', content: json({ $ref: '#/components/schemas/WebhookConfigOutput' }) }, ...errorResponses, '404': { description: 'Integración inexistente', content: json({ $ref: '#/components/schemas/Error' }) } } },
      },
      '/campaigns/batch': { post: { tags: ['Campañas'], summary: 'Sincronizar lote de campañas', security: [{ bearerAuth: [] }], parameters: [integrationHeader, idempotencyHeader], requestBody: { required: true, content: json({ $ref: '#/components/schemas/CampaignBatchInput' }) }, responses: { '202': { description: 'Lote aceptado' }, ...errorResponses } } },
      '/appointments/{externalId}': { put: { tags: ['Agenda'], summary: 'Crear o actualizar cita', security: [{ bearerAuth: [] }], parameters: [{ name: 'externalId', in: 'path', required: true, schema: { type: 'string' } }, integrationHeader, idempotencyHeader], requestBody: { required: true, content: json({ $ref: '#/components/schemas/AppointmentInput' }) }, responses: { '200': { description: 'Cita actualizada' }, '201': { description: 'Cita creada' }, ...errorResponses } } },
      '/deals': { post: { tags: ['Pipeline'], summary: 'Crear o actualizar oportunidad', security: [{ bearerAuth: [] }], parameters: [integrationHeader, idempotencyHeader], requestBody: { required: true, content: json({ $ref: '#/components/schemas/DealInput' }) }, responses: { '200': { description: 'Oportunidad actualizada' }, '201': { description: 'Oportunidad creada' }, ...errorResponses } } },
      '/sync-jobs': { post: { tags: ['Sincronización'], summary: 'Planificar sincronización inicial', security: [{ bearerAuth: [] }], parameters: [integrationHeader, idempotencyHeader], requestBody: { required: true, content: json({ $ref: '#/components/schemas/SyncJobInput' }) }, responses: { '202': { description: 'Plan de sincronización creado' }, ...errorResponses } } },
    },
    components: {
      securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'API key', description: 'Use Authorization: Bearer TU_API_KEY. Nunca envíe la clave en la URL. En las operaciones de recursos incluya también X-Zinto-Integration-Id con el Integration ID UUID que aparece en Configuración → Acceso API → Integraciones CRM.' } },
      schemas: {
        Health: { type: 'object', required: ['status', 'version'], properties: { status: { type: 'string', example: 'ok' }, version: { type: 'string', example: 'v2' } } },
        ContactInput: { type: 'object', required: ['name'], properties: { name: { type: 'string' }, phone: { type: 'string' }, email: { type: 'string', format: 'email' }, company: { type: 'string' }, tags: { type: 'array', items: { type: 'string' } }, customFields: { type: 'object', additionalProperties: true } } },
        MessageInput: { type: 'object', required: ['channelId', 'recipient'], description: 'Debe incluirse exactamente uno de: `text` (opcionalmente junto con `media` como caption), `media`, `template`, `reaction`, `location`, o `interactive`. `reaction`, `location` e `interactive` no admiten `text`. `context.messageId` (responder citando un mensaje) solo se admite junto con `text` por ahora.', properties: { channelId: { type: 'integer', minimum: 1, description: 'ID del canal en Zinto; use GET /channels para listarlos y descubrir el channelId de cada uno.' }, recipient: { type: 'string' }, text: { type: 'string', maxLength: 4096 }, media: { $ref: '#/components/schemas/MessageMediaInput' }, template: { $ref: '#/components/schemas/MessageTemplateInput' }, reaction: { $ref: '#/components/schemas/MessageReactionInput' }, location: { $ref: '#/components/schemas/MessageLocationInput' }, context: { $ref: '#/components/schemas/MessageContextInput' }, interactive: { $ref: '#/components/schemas/MessageInteractiveInput' }, external_message_id: { type: 'string' } } },
        MessageMediaInput: { type: 'object', required: ['url', 'type'], description: 'Requiere el permiso media:upload además de messages:send.', properties: { url: { type: 'string', format: 'uri', description: 'URL http(s) pública del archivo — use la `url` devuelta por POST /media/upload si el archivo no está ya alojado.' }, type: { type: 'string', enum: ['image', 'video', 'audio', 'document'] }, filename: { type: 'string', description: 'Nombre visible del archivo; relevante sobre todo para document.' } } },
        MessageTemplateInput: { type: 'object', required: ['name', 'language'], description: 'Envía una plantilla de WhatsApp ya aprobada en Zinto (esta ruta no crea ni somete plantillas a aprobación). Use `template` para contactar a un destinatario fuera de la ventana de 24 horas, donde WhatsApp rechaza texto o media libres; no requiere ningún permiso adicional a messages:send.', properties: { name: { type: 'string', description: 'Nombre de la plantilla ya aprobada.' }, language: { type: 'string', description: 'Código de idioma de WhatsApp/Meta, p. ej. es o en_US.' }, components: { type: 'array', description: 'Variables de la plantilla; omita el campo por completo si la plantilla no tiene variables.', items: { type: 'object', required: ['type', 'parameters'], properties: { type: { type: 'string', enum: ['header', 'body', 'button'] }, parameters: { type: 'array', items: { oneOf: [{ type: 'string' }, { type: 'object', required: ['type', 'text'], properties: { type: { type: 'string', enum: ['text'] }, text: { type: 'string' } } }] } } } } } } },
        MessageReactionInput: { type: 'object', required: ['messageId', 'emoji'], description: 'Reacciona (o quita la reacción, con emoji vacío) a un mensaje ya intercambiado en el canal. Solo canales WhatsApp Official.', properties: { messageId: { type: 'integer', minimum: 1, description: 'El id (data.id) del mensaje propio al que se reacciona — de esta empresa, no un wamid de Meta.' }, emoji: { type: 'string', description: 'Un único emoji; string vacío para quitar una reacción ya enviada.' } } },
        MessageLocationInput: { type: 'object', required: ['latitude', 'longitude'], description: 'Envía una ubicación estructurada. Solo canales WhatsApp Official.', properties: { latitude: { type: 'number', minimum: -90, maximum: 90 }, longitude: { type: 'number', minimum: -180, maximum: 180 }, name: { type: 'string' }, address: { type: 'string' } } },
        MessageContextInput: { type: 'object', required: ['messageId'], description: 'Responde citando un mensaje previo. Solo admitido junto con `text` por ahora (no con media/template/reaction/location/interactive). Solo canales WhatsApp Official.', properties: { messageId: { type: 'integer', minimum: 1, description: 'El id (data.id) del mensaje propio que se cita — de esta empresa, no un wamid de Meta.' } } },
        MessageInteractiveHeaderInput: {
          type: 'object',
          required: ['type'],
          properties: {
            type: { type: 'string', enum: ['text', 'image', 'video', 'document'] },
            text: { type: 'string', description: 'Requerido cuando type es text.' },
            mediaUrl: { type: 'string', format: 'uri', description: 'Requerido cuando type es image/video/document.' },
          },
        },
        MessageInteractiveButtonInput: {
          type: 'object',
          required: ['id', 'title'],
          properties: { id: { type: 'string' }, title: { type: 'string' } },
        },
        MessageInteractiveListRowInput: {
          type: 'object',
          required: ['id', 'title'],
          properties: { id: { type: 'string' }, title: { type: 'string' }, description: { type: 'string' } },
        },
        MessageInteractiveListSectionInput: {
          type: 'object',
          required: ['rows'],
          properties: {
            title: { type: 'string' },
            rows: { type: 'array', minItems: 1, items: { $ref: '#/components/schemas/MessageInteractiveListRowInput' } },
          },
        },
        MessageInteractiveListInput: {
          type: 'object',
          required: ['button', 'sections'],
          properties: {
            button: { type: 'string', description: 'Texto del botón que despliega la lista.' },
            sections: { type: 'array', minItems: 1, items: { $ref: '#/components/schemas/MessageInteractiveListSectionInput' } },
          },
        },
        MessageInteractiveInput: {
          type: 'object',
          required: ['type', 'body'],
          description: 'Envía botones o una lista interactiva. `buttons` es obligatorio (1-3) cuando type es button; `list` es obligatorio cuando type es list — nunca ambos a la vez. Solo canales WhatsApp Official.',
          properties: {
            type: { type: 'string', enum: ['button', 'list'] },
            body: { type: 'string' },
            header: { $ref: '#/components/schemas/MessageInteractiveHeaderInput' },
            footer: { type: 'string' },
            buttons: { type: 'array', minItems: 1, maxItems: 3, items: { $ref: '#/components/schemas/MessageInteractiveButtonInput' } },
            list: { $ref: '#/components/schemas/MessageInteractiveListInput' },
          },
        },
        MediaUploadOutput: { type: 'object', required: ['url', 'type', 'filename', 'size', 'mimeType'], properties: { url: { type: 'string', format: 'uri' }, type: { type: 'string', enum: ['image', 'video', 'audio', 'document'] }, filename: { type: 'string' }, size: { type: 'integer' }, mimeType: { type: 'string' } } },
        CampaignBatchInput: { type: 'object', required: ['campaigns'], properties: { campaigns: { type: 'array', maxItems: 100, items: { type: 'object', additionalProperties: true } } } },
        AppointmentInput: { type: 'object', required: ['title', 'startsAt', 'endsAt'], properties: { title: { type: 'string' }, startsAt: { type: 'string', format: 'date-time' }, endsAt: { type: 'string', format: 'date-time' }, contactExternalId: { type: 'string' } } },
        DealInput: { type: 'object', required: ['externalId', 'name', 'stage'], properties: { externalId: { type: 'string' }, name: { type: 'string' }, stage: { type: 'string' }, amount: { type: 'number' }, contactExternalId: { type: 'string' } } },
        SyncJobInput: { type: 'object', required: ['resources'], properties: { resources: { type: 'array', items: { type: 'string', enum: ['contacts', 'appointments', 'deals', 'campaigns'] } }, mode: { type: 'string', enum: ['dry_run', 'apply'], default: 'dry_run' } } },
        Channel: { type: 'object', required: ['id', 'name', 'type', 'status'], properties: { id: { type: 'integer' }, name: { type: 'string' }, type: { type: 'string', example: 'whatsapp_official' }, status: { type: 'string', example: 'active' }, phoneNumber: { type: 'string' }, displayName: { type: 'string' }, qualityRating: { type: 'string', enum: ['green', 'yellow', 'red', 'unknown'], description: 'Solo canales WhatsApp Official; se refresca cada hora. Omitido en otros tipos de canal.' }, messagingLimitTier: { type: 'string', example: 'TIER_1K', description: 'Límite de mensajes iniciados por la empresa por 24h, según Meta. Solo WhatsApp Official.' } } },
        ChannelsListOutput: { type: 'object', required: ['data'], properties: { data: { type: 'array', items: { $ref: '#/components/schemas/Channel' } } } },
        Conversation: { type: 'object', required: ['id', 'contactId', 'channelId', 'channelType', 'status', 'isGroup', 'lastMessageAt', 'createdAt'], properties: { id: { type: 'integer' }, contactId: { type: 'integer', nullable: true }, channelId: { type: 'integer' }, channelType: { type: 'string' }, status: { type: 'string', nullable: true }, isGroup: { type: 'boolean', nullable: true }, lastMessageAt: { type: 'string', format: 'date-time', nullable: true }, createdAt: { type: 'string', format: 'date-time', nullable: true } } },
        ConversationsListOutput: { type: 'object', required: ['data', 'total'], properties: { data: { type: 'array', items: { $ref: '#/components/schemas/Conversation' } }, total: { type: 'integer' } } },
        MessageStatusOutput: { type: 'object', required: ['data'], properties: { data: { type: 'object', required: ['status', 'timestamp'], properties: { status: { type: 'string' }, timestamp: { type: 'string', format: 'date-time' } } } } },
        CreateTemplateInput: { type: 'object', required: ['name', 'content', 'connectionId'], properties: { name: { type: 'string', pattern: '^[a-z0-9_]+$', description: 'Solo minúsculas, números y guion bajo (regla de Meta).' }, content: { type: 'string', description: 'Texto del cuerpo de la plantilla; use {{1}}, {{2}}, ... para variables.' }, connectionId: { type: 'integer', minimum: 1, description: 'ID del canal WhatsApp Official (de GET /channels) donde se creará la plantilla.' }, description: { type: 'string' }, whatsappTemplateCategory: { type: 'string', enum: ['utility', 'marketing', 'authentication'], default: 'utility' }, whatsappTemplateLanguage: { type: 'string', default: 'en', description: 'Código de idioma de Meta, p. ej. es o en_US.' }, variables: { type: 'array', description: 'Una entrada por cada {{n}} usado en content.' }, headerType: { type: 'string', enum: ['text', 'image', 'video', 'document'] }, headerText: { type: 'string', description: 'Usado cuando headerType es text.' }, headerMediaUrl: { type: 'string', format: 'uri', description: 'URL pública del archivo de encabezado; requerida cuando headerType es image/video/document.' }, footerText: { type: 'string' } } },
        UpdateTemplateInput: { type: 'object', properties: { description: { type: 'string' }, isActive: { type: 'boolean' } } },
        Template: { type: 'object', required: ['id', 'name', 'content', 'whatsappTemplateStatus'], properties: { id: { type: 'integer' }, name: { type: 'string' }, description: { type: 'string', nullable: true }, content: { type: 'string' }, whatsappTemplateCategory: { type: 'string', nullable: true }, whatsappTemplateStatus: { type: 'string', enum: ['pending', 'approved', 'rejected', 'disabled'], description: 'Estado ante Meta; consulte GET /templates/{templateId} para el valor más reciente.' }, whatsappTemplateId: { type: 'string', nullable: true, description: 'ID asignado por Meta una vez sometida.' }, whatsappTemplateLanguage: { type: 'string', nullable: true }, connectionId: { type: 'integer', nullable: true }, isActive: { type: 'boolean', nullable: true }, usageCount: { type: 'integer', nullable: true }, createdAt: { type: 'string', format: 'date-time', nullable: true } } },
        TemplateOutput: { type: 'object', required: ['data'], properties: { data: { $ref: '#/components/schemas/Template' } } },
        TemplatesListOutput: { type: 'object', required: ['data'], properties: { data: { type: 'array', items: { $ref: '#/components/schemas/Template' } } } },
        WebhookConfigInput: { type: 'object', properties: { url: { type: 'string', format: 'uri', nullable: true, description: 'URL HTTPS pública; null elimina la configurada. Se valida igual que al crear la integración (rechaza destinos privados/locales/reservados).' }, rotateSecret: { type: 'boolean', description: 'true genera un secreto nuevo, invalidando el anterior.' } } },
        WebhookConfigOutput: { type: 'object', required: ['data'], properties: { data: { type: 'object', required: ['url', 'secretConfigured'], properties: { url: { type: 'string', nullable: true }, secretConfigured: { type: 'boolean' }, secret: { type: 'string', description: 'Solo presente cuando se generó un secreto nuevo en esta misma llamada.' } } } } },
        Error: { type: 'object', required: ['error'], properties: { error: { type: 'object', required: ['code', 'message'], properties: { code: { type: 'string' }, message: { type: 'string' }, request_id: { type: 'string' } } } } },
      },
    },
  };
}
